
def get_cbs_cc_query2(account_number):
    q = rf"""
    WITH ENTITY_MAIN_ACCT AS (
  SELECT 
    C.ACCT_SROGT_ID,
    C.ACCT_TITL,
    CAST(D.E_ML_ADDR AS VARCHAR(100)) AS E_ML_ADDR,
    OREPLACE(COALESCE(D.MBL_NUM, D.PHN_BUSN, D.PHN_RSDNC), '[^0-9]') AS MOBILE,
    D.IDNTFTN_VAL,
    D.CUST_SROGT_ID,
    CAST(REGEXP_REPLACE(OTRANSLATE(NULLIF(D.PERM_ADDR,''), ',?\/()-',''),'\s{2,}','') AS VARCHAR(200)) AS PERM_ADDR,
    CAST(REGEXP_REPLACE(OTRANSLATE(D.MLG_ADDR, ',?\/()-',''),'\s{2,}','') AS VARCHAR(200)) AS MLG_ADDR,
    C.SRC_OTHR,
    C.SRC_OF_INCM,
    C.SRC_OF_FUND
  FROM DP_SDMVW_DFDN.DIM_RTAIL_BNK_ACCT_VW C
  INNER JOIN DP_SDMVW_DFDN.DIM_CUST_VW D 
    ON D.CUST_SROGT_ID = C.CUST_SROGT_ID 
   AND D.SYSTEM_CODE = 'CBS'
  WHERE C.ACCT_SROGT_ID = '{account_number}' --'326247471'
    ),

    DIM_CUST AS (
  SELECT *
  FROM (
    SELECT 
      DC.CUST_SROGT_ID,
      DC.IDNTFTN_VAL,
	  C.CUST_TYPE_CD,
      COALESCE(D.OCPTN_DESC, C.CUST_TYPE_DESC) AS OCCUPATION,
      CAST(DC.E_ML_ADDR AS VARCHAR(100)) AS E_ML_ADDR,
      OREPLACE(COALESCE(DC.MBL_NUM, DC.PHN_BUSN, DC.PHN_RSDNC), '[^0-9]') AS NEW_MOBILE,
      CASE 
        WHEN NEW_MOBILE LIKE '0092%' THEN SUBSTR(NEW_MOBILE,5) 
        WHEN NEW_MOBILE LIKE '+92%' THEN SUBSTR(NEW_MOBILE,4) 
        WHEN NEW_MOBILE LIKE '3%' THEN '0'||NEW_MOBILE
        WHEN NEW_MOBILE LIKE '92%' AND LENGTH(NEW_MOBILE)=13 THEN SUBSTR(NEW_MOBILE,3) 
        WHEN NEW_MOBILE LIKE '92%' AND LENGTH(NEW_MOBILE)=12 THEN '0'||SUBSTR(NEW_MOBILE,3)
        ELSE NEW_MOBILE  
      END AS MOBILE,
      CAST(REGEXP_REPLACE(OTRANSLATE(NULLIF(DC.PERM_ADDR,''), ',?\/()-',''),'\s{2,}','') AS VARCHAR(200)) AS PERM_ADDR,
      CAST(REGEXP_REPLACE(OTRANSLATE(DC.MLG_ADDR, ',?\/()-',''),'\s{2,}','') AS VARCHAR(200)) AS MLG_ADDR,
      DC.SYSTEM_CODE,
      CAST(DC.FTHR_NAME AS VARCHAR(100)) AS mothers_name, 
      DC.IDNTFTN_VAL AS ssn, 
      DC.CTRY_OF_NTLTY AS nationality1,
      DC.GNDR AS gender,
      CAST(TRIM(SUBSTRING(REGEXP_REPLACE(DC.CUST_NAME,'^(MR|MRS|MISS|MS|DR)[.]?[ ]*','',1,1,'i') 
           FROM 1 FOR POSITION(' ' IN REGEXP_REPLACE(DC.CUST_NAME,'^(MR|MRS|MISS|MS|DR)[.]?[ ]*','',1,1,'i')||' ')-1)) AS VARCHAR(50)) AS first_name,
      CAST(CASE 
        WHEN TRIM(SUBSTRING(REGEXP_REPLACE(DC.CUST_NAME,'^(MR|MRS|MISS|MS|DR)[.]?[ ]*','',1,1,'i') 
             FROM POSITION(' ' IN REGEXP_REPLACE(DC.CUST_NAME,'^(MR|MRS|MISS|MS|DR)[.]?[ ]*','',1,1,'i')||' ')+1)) = '' 
        THEN TRIM(SUBSTRING(REGEXP_REPLACE(DC.CUST_NAME,'^(MR|MRS|MISS|MS|DR)[.]?[ ]*','',1,1,'i') 
             FROM 1 FOR POSITION(' ' IN REGEXP_REPLACE(DC.CUST_NAME,'^(MR|MRS|MISS|MS|DR)[.]?[ ]*','',1,1,'i')||' ')-1)) 
        ELSE TRIM(SUBSTRING(REGEXP_REPLACE(DC.CUST_NAME,'^(MR|MRS|MISS|MS|DR)[.]?[ ]*','',1,1,'i') 
             FROM POSITION(' ' IN REGEXP_REPLACE(DC.CUST_NAME,'^(MR|MRS|MISS|MS|DR)[.]?[ ]*','',1,1,'i')||' ')+1)) 
      END AS VARCHAR(50)) AS last_name,
      DC.CUST_TYPE_EDW_ID,
      DC.CTRY_OF_NTLTY AS to_country,
      DC.CUST_SROGT_ID AS CUST_NUM, 
      CAST(DC.DT_OF_BIRTH AS VARCHAR(20)) || 'T00:00:00' AS birthdate,
      CASE WHEN DC.MBL_NUM IS NOT NULL THEN 'PAPVT' ELSE 'PAOFF' END AS tph_contact_type,
      CASE WHEN DC.MBL_NUM IS NOT NULL THEN 'COMOB' ELSE 'COOTH' END AS tph_communication_type,
      CASE 
        WHEN DC.MBL_NUM IS NOT NULL AND (SUBSTR(DC.MBL_NUM,0,2)='92' OR SUBSTR(DC.MBL_NUM,1,3)='92') THEN '92'
        WHEN LENGTH(SUBSTR(DC.MBL_NUM,2,12))=10 OR LENGTH(SUBSTR(DC.MBL_NUM,3,13))=10 THEN '92'
        WHEN DC.CTRY_OF_NTLTY='PK' THEN '92'
        ELSE SUBSTR(DC.MBL_NUM,0,2) 
      END AS tph_country_prefix,
      COALESCE(REGEXP_SUBSTR(DC.MBL_NUM,'3.*'), SUBSTR(DC.PHN_BUSN,2,12)) AS tph_number,
      CASE WHEN DC.PERM_ADDR IS NOT NULL THEN 'PAPVT' ELSE 'PAOFF' END AS address_type,
      CAST(COALESCE(DC.MLG_ADDR, DC.PERM_ADDR) AS VARCHAR(200)) AS address,
      DC.CTRY_OF_NTLTY AS country_code,
      C.CUST_TYPE_DESC,
      CAST(CASE 
        WHEN DC.RSDNTL_CITY='0' OR DC.RSDNTL_CITY IS NULL 
        THEN TRIM(REGEXP_SUBSTR(FMC.location,'[A-Z a-z]+')) 
        ELSE DC.RSDNTL_CITY 
      END AS VARCHAR(100)) AS city,
      CAST(COALESCE(DC.RGN_NAME,
          CASE FMC.STATE_LOC
              WHEN 'NW' THEN 'KPK'
              WHEN 'AK' THEN 'AZAD KASHMIR'
              WHEN 'PJ' THEN 'PUNJAB'
              WHEN 'SD' THEN 'SINDH'
              WHEN 'BL' THEN 'BALOCHISTAN'
              WHEN 'IS' THEN 'ISLAMABAD'
              WHEN 'GB' THEN 'GILGIT-BALISTAN'
              WHEN 'FA' THEN 'GILGIT-BALISTAN'
          END
      ) AS VARCHAR(100)) AS state,             
      ROW_NUMBER() OVER(PARTITION BY DC.CUST_SROGT_ID,DC.SYSTEM_CODE ORDER BY DC.START_DATE DESC) AS RN
    FROM DP_SDMVW_DFDN.DIM_CUST_VW DC
    LEFT JOIN dp_wrk_cbs.fm_client_daily FMC ON DC.CUST_SROGT_ID = FMC.client_no 
    LEFT JOIN DP_sDMT_DFDN.DIM_OCPTN D ON D.OCPTN_EDW_ID = DC.OCPTN_EDW_ID AND D.OCPTN_CD IS NOT NULL
    LEFT JOIN DP_SDMT_DFDN.DIM_CUST_TYPE_SS C ON C.CUST_TYPE_EDW_ID = DC.CUST_TYPE_EDW_ID AND C.SYSTEM_CODE = 'CBS'
    LEFT JOIN ENTITY_MAIN_ACCT EM1 ON DC.IDNTFTN_VAL = EM1.IDNTFTN_VAL
    LEFT JOIN ENTITY_MAIN_ACCT EM2 ON OREPLACE(COALESCE(DC.MBL_NUM,DC.PHN_BUSN,DC.PHN_RSDNC),'[^0-9]') = EM2.MOBILE
    LEFT JOIN ENTITY_MAIN_ACCT EM3 ON DC.PERM_ADDR = EM3.PERM_ADDR
    LEFT JOIN ENTITY_MAIN_ACCT EM4 ON DC.MLG_ADDR = EM4.MLG_ADDR
    LEFT JOIN ENTITY_MAIN_ACCT EM5 ON DC.E_ML_ADDR = EM5.E_ML_ADDR
    WHERE DC.SYSTEM_CODE <> 'OMI'
      AND (EM1.IDNTFTN_VAL IS NOT NULL OR EM2.MOBILE IS NOT NULL 
           OR EM3.PERM_ADDR IS NOT NULL OR EM4.MLG_ADDR IS NOT NULL OR EM5.E_ML_ADDR IS NOT NULL)
  ) Q
  WHERE RN = 1
    ),
    RB_RELATED_ACCTS AS (
  SELECT DISTINCT 
    CAST(C.ACCT_SROGT_ID AS VARCHAR(100)) AS ACCT_NO,
	CAST(CUST_TYPE_CD AS VARCHAR (100)) AS CUST_TYPE_CD,
	CAST(CUST_TYPE_DESC AS VARCHAR(100)) AS CUST_TYPE_DESC,
    CAST(C.CUST_SROGT_ID AS VARCHAR(100)) AS CUSTOMER_ID,
    CAST(C.ACCT_TITL AS VARCHAR(200)) AS ACCT_TITLE,
    CAST(TO_CHAR(C.ACCT_OPN_DT,'MM/DD/YYYY') AS VARCHAR(20)) AS ACCT_OPEN_DATE,
    CAST(DA.ACCT_STS_DESC AS VARCHAR(50)) AS ACCT_STATUS,
    CAST(TO_CHAR(C.ACCT_CLS_DT,'MM/DD/YYYY') AS VARCHAR(20)) AS ACCT_CLOSE_DATE,
    CAST(C.BRNCH_SROGT_ID AS VARCHAR(50)) AS BRANCH,
    CAST(C.CURY_EDW_ID AS VARCHAR(10)) AS CCY,
	
	case when D.CUST_TYPE_CD in ('14','06','13','16','15','07','04','30','19','28','25','02','09','38','03',
    '05','10','01','26','21','18','12','24','20','29','22','23','08','27','31') then 'ARCTA' 
    when C.JOIN_ACCT_FLG = '1' then 'ARJTA'
    when D.CUST_TYPE_CD = ('11') then 'ARMRB' else 'ARCTA' end as Role_,

    CASE WHEN C.ACCT_STS_EDW_ID = 'A' then 'ASACT'  when C.ACCT_STS_EDW_ID = 'C' then 'ASCBC' 
				when C.ACCT_STS_EDW_ID = 'I' then 'ASINA'   when C.ACCT_STS_EDW_ID = 'N' THEN 'ASNAC' 
				when C.ACCT_STS_EDW_ID = 'D' THEN 'ASDOR'
				ELSE 'ASOTH' END AS STATUS_CODE,

    CAST(TRIM(COALESCE(
      CASE WHEN EM.SRC_OF_FUND IN ('1','2','3') THEN D.OCCUPATION ELSE OREPLACE(EM.SRC_OF_FUND,'_') END
    ,'-')) AS VARCHAR(200)) AS SOURCE_OF_FUNDS,
    CAST(D.IDNTFTN_VAL AS VARCHAR(30)) AS CNIC,
    CAST(D.MOBILE AS VARCHAR(30)) AS MOBILE,  
    CAST(D.MLG_ADDR AS VARCHAR(200)) AS MAILING_ADDRESS,
    CAST(D.E_ML_ADDR AS VARCHAR(100)) AS EMAIL_ADDRESS,
    CAST(D.PERM_ADDR AS VARCHAR(200)) AS PERMANENT_ADDRESS,
    CAST(D.SYSTEM_CODE AS VARCHAR(10)) AS SYSTEM_CODE,
    CAST(CASE 
      WHEN D.MOBILE = EM.MOBILE AND EM.MOBILE <> '' THEN 'Mobile Matched'
      WHEN D.E_ML_ADDR = EM.E_ML_ADDR AND EM.E_ML_ADDR <> '' THEN 'Email Matched'
      WHEN D.IDNTFTN_VAL = EM.IDNTFTN_VAL AND EM.IDNTFTN_VAL <> '' THEN 'CNIC Matched'
      WHEN D.PERM_ADDR = EM.PERM_ADDR AND D.PERM_ADDR <> '' THEN 'Address Matched'
    END AS VARCHAR(50)) AS Reason,
    CAST(mothers_name AS VARCHAR(100)) AS mothers_name,
    CAST(ssn AS VARCHAR(30)) AS ssn,
    CAST(nationality1 AS VARCHAR(50)) AS nationality1,
    CAST(gender AS VARCHAR(10)) AS gender,
    CAST(first_name AS VARCHAR(50)) AS first_name,
    CAST(last_name AS VARCHAR(50)) AS last_name,
    CAST(to_country AS VARCHAR(50)) AS to_country,
    CAST(birthdate AS VARCHAR(20)) AS birthdate,
    CAST(tph_contact_type AS VARCHAR(20)) AS tph_contact_type,
    CAST(tph_communication_type AS VARCHAR(20)) AS tph_communication_type,
    CAST(tph_country_prefix AS VARCHAR(10)) AS tph_country_prefix,
    CAST(tph_number AS VARCHAR(30)) AS tph_number,
    CAST(address_type AS VARCHAR(20)) AS address_type,
    CAST(D.address AS VARCHAR(200)) AS address,
    CAST(country_code AS VARCHAR(10)) AS country_code,
    CAST(city AS VARCHAR(100)) AS city,
    CAST(state AS VARCHAR(100)) AS state,
    CAST(COALESCE(
      NULLIF(TRIM(EM.SRC_OTHR),''),
      NULLIF(TRIM(EM.SRC_OF_INCM),''),
      NULLIF(TRIM(EM.SRC_OF_FUND),''),
      D.CUST_TYPE_DESC
    ) AS VARCHAR(200)) AS occupation,
    CAST(R.NRRTV AS VARCHAR(200)) AS NRRTV,
    CAST(R.RSTRNT_TYPE_EDW_ID AS VARCHAR(50)) AS RSTRNT_TYPE_EDW_ID
  FROM ENTITY_MAIN_ACCT EM 
  LEFT JOIN DIM_CUST D  
    ON ((D.MOBILE = EM.MOBILE AND EM.MOBILE <> '') 
     OR (D.E_ML_ADDR = EM.E_ML_ADDR AND EM.E_ML_ADDR <> '')
     OR (D.IDNTFTN_VAL = EM.IDNTFTN_VAL AND EM.IDNTFTN_VAL <> '') 
     OR (D.PERM_ADDR = EM.PERM_ADDR AND D.PERM_ADDR <> '')) 
   AND D.SYSTEM_CODE = 'CBS'  
  LEFT JOIN DP_SDMVW_DFDN.DIM_RTAIL_BNK_ACCT_VW C 
    ON D.CUST_SROGT_ID = C.CUST_SROGT_ID AND D.SYSTEM_CODE = 'CBS'  
  LEFT JOIN DP_sDMT_DFDN.DIM_ACCT_STS_SS DA 
    ON DA.ACCT_STS_EDW_ID = C.ACCT_STS_EDW_ID AND DA.SYSTEM_CODE = 'CBS'
  LEFT JOIN (
    SELECT ACCT_SROGT_ID, NRRTV, RSTRNT_TYPE_EDW_ID
    FROM (
      SELECT ACCT_SROGT_ID, NRRTV, RSTRNT_STRT_DT, RSTRNT_TYPE_EDW_ID,
             ROW_NUMBER() OVER(PARTITION BY ACCT_SROGT_ID ORDER BY RSTRNT_STRT_DT DESC) AS RN
      FROM DP_SDMVW_DFDN.FCT_RTAIL_BNK_ACCT_RSTRNT_VW
      WHERE RSTRNT_TYPE_EDW_ID = 'RFA'
        AND RSTRNT_STS = 'A'
        AND cast(BATCH_DT as date) = CURRENT_DATE-1
    ) Q
    WHERE RN=1
  ) R ON C.ACCT_SROGT_ID = R.ACCT_SROGT_ID
  --where  c.ACCT_SROGT_ID <> '{account_number}'

  UNION ALL

  SELECT DISTINCT
    CAST(DC.CARD_NUM AS VARCHAR(100)) AS ACCT_NO,
		'' AS CUST_TYPE_CD,
	'' AS CUST_TYPE_DESC,
    CAST(DC.CUST_SROGT_ID AS VARCHAR(100)) AS CUSTOMER_ID,
    CAST(DC.EMBS_NAME AS VARCHAR(200)) AS ACCT_TITL,
    CAST(TO_CHAR(DC.CARD_CRTN_DT,'MM/DD/YYYY') AS VARCHAR(20)) AS ACCT_OPEN_DATE,
    CAST(DA.ACCT_STS_DESC AS VARCHAR(50)) AS ACCT_STATUS,
    CAST(TO_CHAR(DC.CARD_CLSUR_DT,'MM/DD/YYYY') AS VARCHAR(20)) AS ACCT_CLOSE_DATE,
    'UBL Credit Card HO' AS BRANCH,
	    'PKR' AS CCY,
    ' ' AS ROLE_,
	'' AS STATUS_CODE,
    CAST(D.OCCUPATION AS VARCHAR(200)) AS SOURCE_OF_FUNDS,
    CAST(D.IDNTFTN_VAL AS VARCHAR(30)) AS CNIC,
    CAST(D.MOBILE AS VARCHAR(30)) AS MOBILE,  
    CAST(D.MLG_ADDR AS VARCHAR(200)) AS MAILING_ADDRESS,
    CAST(D.E_ML_ADDR AS VARCHAR(100)) AS EMAIL_ADDRESS,
    CAST(D.PERM_ADDR AS VARCHAR(200)) AS PERMANENT_ADDRESS,
    CAST(D.SYSTEM_CODE AS VARCHAR(10)) AS SYSTEM_CODE,
    CAST('CNIC Matched' AS VARCHAR(50)) AS Reason,
    CAST(mothers_name AS VARCHAR(100)) AS mothers_name,
    CAST(ssn AS VARCHAR(30)) AS ssn,
    CAST(nationality1 AS VARCHAR(50)) AS nationality1,
    CAST(gender AS VARCHAR(10)) AS gender,
    CAST(first_name AS VARCHAR(50)) AS first_name,
    CAST(last_name AS VARCHAR(50)) AS last_name,
    CAST(to_country AS VARCHAR(50)) AS to_country,
    CAST(birthdate AS VARCHAR(20)) AS birthdate,
    CAST(tph_contact_type AS VARCHAR(20)) AS tph_contact_type,
    CAST(tph_communication_type AS VARCHAR(20)) AS tph_communication_type,
    CAST(tph_country_prefix AS VARCHAR(10)) AS tph_country_prefix,
    CAST(tph_number AS VARCHAR(30)) AS tph_number,
    CAST(address_type AS VARCHAR(20)) AS address_type,
    CAST(D.address AS VARCHAR(200)) AS address,
    CAST(country_code AS VARCHAR(10)) AS country_code,
    CAST(city AS VARCHAR(100)) AS city,
    CAST(state AS VARCHAR(100)) AS state,
    CAST('' AS VARCHAR(200)) AS occupation,
    CAST('' AS VARCHAR(200)) AS NRRTV,
    CAST('' AS VARCHAR(50)) AS RSTRNT_TYPE_EDW_ID
   FROM  DP_SDMT_DFDN.DIM_CARD_SS DC
    LEFT JOIN DIM_CUST D ON D.CUST_sROGT_ID = DC.CUST_sROGT_ID AND D.SYSTEM_CODE = 'CTL'
    LEFT JOIN DP_sDMT_DFDN.DIM_ACCT_STS_SS DA ON DA.ACCT_STS_EDW_ID = DC.CARD_STS_EDW_ID AND DA.SYSTEM_cODE = 'CTL'
    WHERE DC.SYSTEM_CODE = 'CTL'
    AND D.IDNTFTN_VAL IN (SELECT IDNTFTN_VAL FROM ENTITY_MAIN_ACCT)
    ),

    FACT_TRXNS AS (
  SELECT 
    CAST(ACCT_SROGT_ID AS VARCHAR(100)) AS ACCT_NO,
    SUM(CREDIT_AMT) AS CREDIT_AMT,
    SUM(DEBIT_AMT) AS DEBIT_AMT,
    SUM(NO_OF_CREDITS) AS NO_OF_CREDITS,
    SUM(NO_OF_DEBITS) AS NO_OF_DEBITS
  FROM (
    SELECT DISTINCT 
      CAST(ACCT_SROGT_ID AS VARCHAR(100)) AS ACCT_SROGT_ID, 
      TSACTN_ID,
      CASE WHEN CR_DR_IND = 'C' AND SRC_TYP <> 'NI' THEN TSACTN_AMT ELSE 0 END AS CREDIT_AMT,
      CASE WHEN CR_DR_IND = 'D' THEN TSACTN_AMT ELSE 0 END AS DEBIT_AMT,
      CASE WHEN CR_DR_IND = 'C' AND SRC_TYP <> 'NI' THEN 1 ELSE 0 END AS NO_OF_CREDITS,
      CASE WHEN CR_DR_IND = 'D' THEN 1 ELSE 0 END AS NO_OF_DEBITS
    FROM DP_SDMVW_DFDN.FCT_RTAIL_BNK_TSACTN_VW  
    INNER JOIN RB_RELATED_ACCTS RB ON ACCT_SROGT_ID = RB.ACCT_NO
    WHERE CAST(TSACTN_TMSTP AS DATE) BETWEEN ADD_MONTHS(CURRENT_DATE-1,-36) AND CURRENT_DATE-1
      AND RVSL_SEQ_NUM IS NULL 
      AND Reveral_IND = 'N'
  ) A
  GROUP BY ACCT_SROGT_ID

  UNION ALL

  SELECT 
    CAST(ACCT_NO AS VARCHAR(100)) AS ACCT_NO,
    SUM(CREDIT_AMT) AS CREDIT_AMT,
    SUM(DEBIT_AMT) AS DEBIT_AMT,
    SUM(NO_OF_CREDITS) AS NO_OF_CREDITS,
    SUM(NO_OF_DEBITS) AS NO_OF_DEBITS
  FROM (
    SELECT 
      CAST(FCT.CARD_NUM AS VARCHAR(100)) AS ACCT_NO,
      CASE WHEN TSACTN_AMT > 0 THEN TSACTN_AMT ELSE 0 END AS CREDIT_AMT,
      CASE WHEN TSACTN_AMT <= 0 THEN TSACTN_AMT * -1 ELSE 0 END AS DEBIT_AMT,
      CASE WHEN TSACTN_AMT > 0 THEN 1 ELSE 0 END AS NO_OF_CREDITS,
      CASE WHEN TSACTN_AMT <= 0 THEN 1 ELSE 0 END AS NO_OF_DEBITS                           
    FROM DP_SDMT_DFDN.FCT_CR_CARD_TSACTN FCT
    INNER JOIN RB_RELATED_ACCTS RB ON FCT.CARD_NUM = RB.ACCT_NO
    WHERE CAST(TSACTN_DT AS DATE) BETWEEN ADD_MONTHS(CURRENT_DATE-1,-36) AND CURRENT_DATE-1
  ) Q
  GROUP BY ACCT_NO
    ),


    FINAL_OUTPUT AS (
    SELECT 
  CAST(RB.ACCT_NO AS VARCHAR(100)) AS ACCT_NO,
  CAST(RB.CUSTOMER_ID AS VARCHAR(100)) AS CUSTOMER_ID,
  CAST(RB.ACCT_TITLE AS VARCHAR(200)) AS ACCT_TITLE,
  CAST(RB.CUST_TYPE_CD  AS VARCHAR(200)) AS CUSTOMER_TYPE_CODE,
  CAST(RB.CUST_TYPE_DESC AS VARCHAR(200)) AS CUSTOMER_TYPE_DESC,
  'UNITED BANK LIMITED ' as institution_name, 
  'UNILPKKA' as swift,
  CASE WHEN RSTRNT_TYPE_EDW_ID IS NOT NULL 
       THEN CAST('B' AS VARCHAR(5)) 
       ELSE CAST(RB.ACCT_STATUS AS VARCHAR(50)) END AS ACCT_STATUS,
  CAST(RB.ACCT_OPEN_DATE AS VARCHAR(20)) AS ACCT_OPEN_DATE,
  COALESCE(CAST(RB.ACCT_CLOSE_DATE AS VARCHAR(20)),'-') AS ACCT_CLOSE_DATE,
  CAST(RB.BRANCH AS VARCHAR(50)) AS BRANCH,
  CAST(RB.STATUS_CODE AS VARCHAR(100)) AS STATUS_CODE,
  CAST(RB.CCY AS VARCHAR(10)) AS CCY,
  CAST(Role_ AS VARCHAR(100)) AS "ROLE",
  CAST(RB.SOURCE_OF_FUNDS AS VARCHAR(200)) AS SOURCE_OF_FUNDS,
  CAST(RB.CNIC AS VARCHAR(30)) AS CNIC,
  CAST(RB.MOBILE AS VARCHAR(30)) AS MOBILE,  
  CAST(RB.MAILING_ADDRESS AS VARCHAR(200)) AS MAILING_ADDRESS,
  CAST(RB.EMAIL_ADDRESS AS VARCHAR(100)) AS EMAIL_ADDRESS,
  CAST(RB.PERMANENT_ADDRESS AS VARCHAR(200)) AS PERMANENT_ADDRESS,
  CAST(RB.Reason AS VARCHAR(50)) AS Reason,
  COALESCE(FT.NO_OF_CREDITS,0) AS NO_OF_CREDITS,
  COALESCE(FT.CREDIT_AMT,0) AS CREDIT_AMT,
  COALESCE(FT.NO_OF_DEBITS,0) AS NO_OF_DEBITS,
  COALESCE(FT.DEBIT_AMT,0) AS DEBIT_AMT,
  CAST(RB.mothers_name AS VARCHAR(100)) AS mothers_name,
  CAST(RB.ssn AS VARCHAR(30)) AS ssn,
  CAST(RB.nationality1 AS VARCHAR(50)) AS nationality1,
  CAST(RB.gender AS VARCHAR(10)) AS gender,
  CAST(RB.first_name AS VARCHAR(50)) AS first_name,
  CAST(RB.last_name AS VARCHAR(50)) AS last_name,
  CAST(RB.to_country AS VARCHAR(50)) AS to_country,
  CAST(RB.birthdate AS VARCHAR(20)) AS birthdate,
  CAST(RB.tph_contact_type AS VARCHAR(20)) AS tph_contact_type,
  CAST(RB.tph_communication_type AS VARCHAR(20)) AS tph_communication_type,
  CAST(RB.tph_country_prefix AS VARCHAR(10)) AS tph_country_prefix,
  CAST(RB.tph_number AS VARCHAR(30)) AS tph_number,
  CAST(RB.address_type AS VARCHAR(20)) AS address_type,
  CAST(RB.address AS VARCHAR(200)) AS address,
  CAST(RB.country_code AS VARCHAR(10)) AS country_code,
  CAST(RB.city AS VARCHAR(100)) AS city,
  CAST(RB.state AS VARCHAR(100)) AS state,
  CAST(RB.occupation AS VARCHAR(200)) AS occupation,
  CAST(RB.NRRTV AS VARCHAR(200)) AS NRRTV,
  CAST(RB.RSTRNT_TYPE_EDW_ID AS VARCHAR(50)) AS RSTRNT_TYPE_EDW_ID
    FROM RB_RELATED_ACCTS RB
    LEFT JOIN FACT_TRXNS FT ON FT.ACCT_NO = RB.ACCT_NO
    --WHERE RB.ACCT_NO <> '{account_number}'

    )
    SELECT * FROM FINAL_OUTPUT
    --where acct_no <> '{account_number}'

   
   
   
    """

    return q

